[lib]
crate-type = ["cdylib", "rlib"]

[package]
name = "redmoon"
version = "0.1.0"
edition = "2021"

[dependencies]
ordered-float = "3.4.0"

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.2"
web-sys = "0.3.61"

[dependencies.web-sys]
features = ["console"]