#[derive(PartialEq)]
#[derive(Clone)]
pub enum Token {
    Assign,
    LiteralNumber(f32),
    LiteralString(String),
    True,
    False,
    Nil,
    Plus,
    Minus,
    Star,
    ForwardSlash,
    Equals,
    NotEquals,
    LessThan,
    GreaterThan,
    LessThanOrEqual,
    GreaterThanOrEqual,
    Not,
    LeftParens,
    RightParens
}
